In [19]:
import numpy as np
import scipy.linalg as linalg
from scipy.sparse import linalg as spla
import scipy.sparse as sparse
import timeit

In [32]:
def error (approx , exact ):
    return linalg . norm ( approx - exact )/n
def solver_wrapper (a, b, solver ="general"):
    if solver == "inv":
        a_inv = linalg.inv (a)
        return a_inv @ b
    elif solver == "general":
        return linalg.solve (a, b)
    elif solver == "spd":
        return linalg.solve (a, b, assume_a ="pos")
    elif solver == "toeplitz":
        return linalg.solve_toeplitz (a[0, :], b)
    elif solver == "sparse_inv":
        a_inv = spla.inv (a)
        return a_inv @ b
    elif solver == "sparse_general":
        return spla.spsolve (a, b)
    elif solver == "cg":
        return spla.cg(a, b, maxiter =50) [0]
    else :
        raise Exception (" Unknown solver ")


In [50]:
A = np.array([[2, - 1 , 2], 
                [-1, 2, -1], 
                [ 2 ,-1, 2],
                  [-1 ,2, -1]])
x = np.array([1, 0, 1])


print(A@x)

[ 4 -2  4 -2]


In [33]:
def experiment (solver , a, b, num_runs ):
    print ("\ nSolver : {}".format( solver ), end ="\n"+"-" *25+ "\n")
    wall_time = timeit.timeit('x = solver_wrapper (a,b, solver = solver )',globals = globals() , number = num_runs )
    print (" Time :     {:2.2f} seconds ".format( wall_time ))
    x = solver_wrapper (a, b, solver = solver )
    print (" Error :        {:.2e}".format(error(x, exact )))



In [35]:
n = 2500
b = np.zeros(n) # 1 * 2500  --- vector b
b[0] , b[ -1] = 1, 1
exact = np.ones(n) # actual matmul of A * b is 1,1,1,1,1,.......
num_runs = 5

# DENSE
a = -np.eye(n, k= -1) + 2 * np.eye(n) + -np.eye(n, k =1) # 2500 * 2500 --- matrix a
solvers = ("inv", "general", "spd", "toeplitz", "cg") 
for solver in solvers :
    #print(solver)
    experiment ( solver , a, b, num_runs )

# SPARSE
a = sparse.csr_matrix(a)
sparse_solvers = ("sparse_inv", "sparse_general", "cg")
for solver in sparse_solvers :
    experiment ( solver , a, b, num_runs )

inv
\ nSolver : inv
-------------------------
 Time :     2.16 seconds 
 Error :        2.13e-14
general
\ nSolver : general
-------------------------
 Time :     0.92 seconds 
 Error :        2.12e-14
spd
\ nSolver : spd
-------------------------
 Time :     0.77 seconds 
 Error :        4.34e-14
toeplitz
\ nSolver : toeplitz
-------------------------
 Time :     0.08 seconds 
 Error :        1.00e-13
cg
\ nSolver : cg
-------------------------
 Time :     0.64 seconds 
 Error :        1.97e-02
\ nSolver : sparse_inv
-------------------------


C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:322: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
C:\Users\looka\AppData\Roaming\Python\Python310\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:215: SparseEfficiencyWarning: spsolve is more efficient when sparse b is in the CSC matrix format
  warn('spsolve is more efficient when sparse b '


 Time :     3.33 seconds 
 Error :        2.13e-14
\ nSolver : sparse_general
-------------------------
 Time :     0.01 seconds 
 Error :        2.13e-14
\ nSolver : cg
-------------------------
 Time :     0.01 seconds 
 Error :        1.97e-02


In [64]:
m = 3
a = -np.eye (4, k= -1) + 2 * np.eye (4) + -np.eye (4, k =1)


In [66]:
b = np. zeros (4)
b[0] , b[ -1] = 1, 1
b

array([1., 0., 0., 1.])

In [65]:
a@b

array([ 2., -1., -1.,  2.])

In [ ]:
if __name__ == " __main__ ":
    n = 2500
    b = np. zeros (n)
    b[0] , b[ -1] = 1, 1
    exact = np.ones (n) ### assumeed actual result
    num_runs = 5

    # DENSE
    a = -np.eye (n, k= -1) + 2 * np.eye (n) + -np.eye (n, k =1) # one step lower diagonal (k = -1) + one step upper diagonal(k = 1)
    solvers = (" inv", " general ", " spd", " toeplitz ", "cg")
    for solver in solvers :
        experiment ( solver , a, b, num_runs )

    # SPARSE
    a = sparse . csr_matrix (a)
    sparse_solvers = (" sparse_inv ", " sparse_general ", "cg")
    for solver in sparse_solvers :
        experiment ( solver , a, b, num_runs )