In [3]:
import numpy as np
from scipy import sparse

In [4]:
n = int(1e3)
n

1000

In [9]:
x = np.random.rand (n)
x.shape

(1000,)

In [ ]:
A = 2 * sparse.eye(5) - sparse.eye(5, k=1) - sparse.eye(5, k= -1)

b = [0] * ( len(A. indptr ) - 1)
for i, pair in enumerate ( zip(A. indptr [0: -1] , A. indptr [1:]) ): ### row pointer --- indptr (row pointer)
            print('i: ',i,' pair: ',pair, '\n' ) ### pair from indptr e.g - (0,2) (2,5) (5,8) ..... for pointing the indecies and get the data
            for a_ij , j in zip (A. data [ pair [0]: pair [1]] ,
                                A. indices [ pair [0]: pair [1]]) : ### column pointer --- indecies
                                #### for pair (0, 2) --- loop will run 2 times for (0,0) (0,1) --- 0th row in column 0, 1 have non zero values
                                ### for pair (5,8) ---5th value start at row 2 so loop will run  (2,1) (2,2), (2,3) and  1,2,3 means at indieces 1,2,3 we have non zero values
                                #### A.data giving the value of 0th and 1th location from data array
                                #### A .indieces telling which columns of ith row has this values e.g - for 0th row the value is in 0, 1 column
                print('a_ij: ',a_ij,' j: ',j, '\n' ) ## a_ij = value in ith row and jth column
                b[i] += a_ij * x[j]

In [ ]:
A. indptr [0: -1]

In [ ]:
A. indptr [1:]

In [ ]:
A.toarray()

In [ ]:
print(A.data)
print(A.indices)
print(A.indptr)


In [ ]:
b = [0] * ( len(A. indptr ) - 1)
b

In [5]:
n = 5
delta = 1.0
A = np.tril (np. random . rand (n,n) -0.5) + delta * np. eye (n) ### tril -- lower triangular of an array

In [18]:
print(A.diagonal())
np. min( abs(A. diagonal ()))

[0.84613166 0.59056853 1.2657805  1.45214275 0.7680628 ]


0.5905685326983553

In [ ]:
m = n =  5
m, n = A. shape
nb = len (b)
d = A. diagonal ()

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### condition number of a matrix

In [13]:
from numpy import linalg as la 

In [14]:
a = np.array([[ 1, 1, 0],
   [1, 0, 1],
   [1, 0, 0]])
print("Our Array...\n",a)

Our Array...
 [[1 1 0]
 [1 0 1]
 [1 0 0]]


In [17]:
print("\nDimensions of our Array...\n",a.ndim)
print("\nDatatype of our Array object...\n",a.dtype)
print("\nShape of our Array object...\n",a.shape)
print("\ncondition number...\n",la.cond(a))


Dimensions of our Array...
 2

Datatype of our Array object...
 int32

Shape of our Array object...
 (3, 3)

condition number...
 3.7320508075688776


### upper triangular

In [36]:
def solve_low(A, b):
    x = np. zeros (3)
        # solve for lower triangular matrix
    for i in range (3):
        print('i: ', i,'\n')
        for j in range (i):
            print('j: ', j,'\n')
            print('1. / A[i, i]: ',1. / A[i, i],' -A[i, j]: ', -A[i, j], 'x[j]: ', x[j],  '-A[i, j] * x[j]: ', -A[i, j] * x[j], '\n')
            x[i] += 1. / A[i, i] * (-A[i, j] * x[j])
        print('A[i, i]: ', A[i, i], 'b[i]: ', b[i], 'x[i]: ', 1. / A[i, i] * b[i], '\n\n\n')
        x[i] += 1. / A[i, i] * b[i]
    return x

In [ ]:
## Test dimension mismatch
#A = np.tril(np.arange(3*3).reshape(3,3))
b = [1, 2, 3]
##solve_low (A, b)
print(A)
print(b)
##print(solve_low (A, b))

x[1] += 1. / A[i, i] * (-A[i, j] * x[j])



In [61]:
grid = np. linspace (-1, 1, 3)
A = np. vander (grid , 2 , increasing = True )
A

array([[ 1., -1.],
       [ 1.,  0.],
       [ 1.,  1.]])

In [60]:
A[:, 0] #

array([1., 1., 1., 1., 1.])

In [65]:
m, n = A. shape
R = np. zeros ((n, n))
Q = np. zeros ((m, n))
R[0, 0] = np. linalg . norm (A[:, 0])
Q[:, 0] = A[:, 0] / R[0, 0]
print(Q)
print('\n\n\n')
print(R)


for k in range (1, n):
        print('k: ', k)
        for l in range (0, k):
            print('l: ', l)
            print('A[:, k]', A[:, k])
            print('Q[:, l]: ', Q[:, l])
            R[l, k] = A[:, k] @ Q[:, l]
            print('R[l, k]: ', R[l, k] )
        q = A[:, k] - Q @ R[:, k]
        print('q: ', q)
        R[k, k] = np. linalg . norm (q)### norm value at (1, 1)
        print('R[k,k]: ',R[k,k])
        Q[:, k] = q / R[k, k]
        print('Q[:, k]: ',R[k,k])
        ##print('\n\n\n')

[[0.57735027 0.        ]
 [0.57735027 0.        ]
 [0.57735027 0.        ]]




[[1.73205081 0.        ]
 [0.         0.        ]]
k:  1
l:  0
A[:, k] [-1.  0.  1.]
Q[:, l]:  [0.57735027 0.57735027 0.57735027]
R[l, k]:  0.0
q:  [-1.  0.  1.]
R[k,k]:  1.4142135623730951
Q[:, k]:  1.4142135623730951


In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [64]:
print(Q)
print(R)

[[ 0.57735027 -0.70710678]
 [ 0.57735027  0.        ]
 [ 0.57735027  0.70710678]]
[[1.73205081 0.        ]
 [0.         1.41421356]]
